services:
  api-productos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:

      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

    restart: unless-stopped
